# Generated by Django 6.0.1 on 2026-01-30 20:45

import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('password_hash', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='users_email_ci_unique')],
            },
        ),
    ]
